#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
MANIFEST_DIR="$REPO_ROOT/manifest"
SCRIPTS_DIR="$REPO_ROOT/scripts"

log() { echo "[export] $*"; }

check_deps() {
  for cmd in pacman yay jq; do
    command -v "$cmd" &>/dev/null || { log "Missing dependency: $cmd"; exit 1; }
  done
}

get_pacman_packages() {
  pacman -Qe | awk '{print $1}' | sort
}

get_aur_packages() {
  yay -Qm | awk '{print $1}' | sort
}

build_manifest() {
  local pacman_pkgs="$1"
  local aur_pkgs="$2"
  local timestamp
  timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

  local pacman_json aur_json
  pacman_json="$(echo "$pacman_pkgs" | jq -R . | jq -s .)"
  aur_json="$(echo "$aur_pkgs" | jq -R . | jq -s .)"

  jq -n \
    --argjson pacman "$pacman_json" \
    --argjson aur "$aur_json" \
    --arg ts "$timestamp" \
    '{generated_at: $ts, pacman: $pacman, aur: $aur}' \
    > "$MANIFEST_DIR/packages.json"

  log "Manifest written to $MANIFEST_DIR/packages.json"
}

generate_install_script() {
  local pacman_pkgs="$1"
  local aur_pkgs="$2"
  local timestamp
  timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  local out="$SCRIPTS_DIR/install-packages.sh"

  # Build the pacman package list as indented lines for the script
  local pacman_lines=""
  while IFS= read -r pkg; do
    [[ -z "$pkg" ]] && continue
    pacman_lines+="    $pkg \\"$'\n'
  done <<< "$pacman_pkgs"
  # Strip trailing backslash-newline from last entry
  pacman_lines="${pacman_lines%\\$'\n'}"

  local aur_lines=""
  while IFS= read -r pkg; do
    [[ -z "$pkg" ]] && continue
    aur_lines+="    $pkg \\"$'\n'
  done <<< "$aur_pkgs"
  aur_lines="${aur_lines%\\$'\n'}"

  # Count AUR packages for the guard
  local aur_count=0
  if [[ -n "$aur_pkgs" ]]; then
    aur_count="$(echo "$aur_pkgs" | grep -c '.' || true)"
  fi

  {
    cat <<HEADER
#!/usr/bin/env bash
set -euo pipefail
# AUTO-GENERATED by export/export.sh — do not edit by hand
# Generated at: ${timestamp}

log() { echo "[install-packages] \$*"; }

install_pacman_packages() {
  log "Installing pacman packages..."
  sudo pacman -S --needed --noconfirm \\
HEADER

    echo "$pacman_lines"

    cat <<'PACMAN_END'

}

PACMAN_END

    if [[ "$aur_count" -gt 0 ]]; then
      cat <<AUR_START
install_aur_packages() {
  log "Installing AUR packages..."
  yay -S --needed --noconfirm \\
AUR_START

      echo "$aur_lines"

      cat <<'AUR_END'

}

AUR_END
    else
      cat <<'AUR_EMPTY'
install_aur_packages() {
  log "No AUR packages to install."
}

AUR_EMPTY
    fi

    cat <<'FOOTER'
install_pacman_packages
install_aur_packages
log "Done."
FOOTER
  } > "$out"

  chmod +x "$out"
  log "Install script written to $out"
}

main() {
  check_deps
  mkdir -p "$MANIFEST_DIR" "$SCRIPTS_DIR"

  log "Querying pacman packages..."
  local pacman_pkgs
  pacman_pkgs="$(get_pacman_packages)"

  log "Querying AUR packages..."
  local aur_pkgs
  aur_pkgs="$(get_aur_packages)"

  log "Building manifest..."
  build_manifest "$pacman_pkgs" "$aur_pkgs"

  log "Generating install script..."
  generate_install_script "$pacman_pkgs" "$aur_pkgs"

  log "Export complete. Review and commit manifest/ and scripts/:"
  log "  git add manifest/ scripts/ && git commit -m 'export: update package manifest'"
}

main "$@"
