#!/usr/bin/env bash
set -euo pipefail
# AUTO-GENERATED by export/export.sh — do not edit by hand
# Run export/export.sh to regenerate this file.

echo "[install-packages] No packages manifest yet. Run export/export.sh first." >&2
exit 1
