#!/usr/bin/env bash
set -euo pipefail
# AUTO-GENERATED by export/export.sh — do not edit by hand
# Generated at: 2026-04-22T10:18:09Z

log() { echo "[install-packages] $*"; }

sync_pacman_db() {
  log "Syncing pacman package databases..."
  sudo pacman -Sy
}

setup_mirrors() {
  if command -v reflector &>/dev/null; then
    log "reflector already installed, updating mirrors..."
  else
    log "Installing reflector to select fast mirrors..."
    sudo pacman -S --needed --noconfirm reflector
  fi
  log "Selecting fastest mirrors (this may take a moment)..."
  sudo reflector --latest 10 --sort rate --protocol https --save /etc/pacman.d/mirrorlist
  sudo pacman -Sy
  log "Mirrors updated."
}

install_yay() {
  if command -v yay &>/dev/null; then
    log "yay already installed, skipping."
    return
  fi
  log "Installing yay from AUR..."
  sudo pacman -S --needed --noconfirm base-devel git
  local yay_dir="/tmp/yay"
  if [[ ! -d "$yay_dir" ]]; then
    git clone https://aur.archlinux.org/yay.git "$yay_dir"
  fi
  (cd "$yay_dir" && makepkg -si --noconfirm)
  log "yay installed."
}

install_pacman_packages() {
  log "Installing pacman packages..."
  sudo pacman -S --needed --noconfirm \
    azure-cli \
    base \
    base-devel \
    dos2unix \
    fd \
    fzf \
    git \
    jq \
    luarocks \
    neovim \
    nodejs \
    npm \
    openssh \
    python \
    python-pip \
    python-pipx \
    ripgrep \
    sudo \
    terraform \
    unzip \
    wget \
    xdg-utils \
    zellij \
    zsh 

}

install_aur_packages() {
  log "Installing AUR packages..."
  yay -S --needed --noconfirm \
    wslu \
    yay \
    yay-debug 

}

sync_pacman_db
setup_mirrors
install_yay
install_pacman_packages
install_aur_packages
log "Done."
